const log = console.log;
log("==start==");
let prices = [0.1, 0.02, 0.93];
log(prices);
let doublePrices = Array.from("127578954892").map((v) => (+v) * 10);
log(doublePrices);
doublePrices = doublePrices.map((v) => v * 2.02);
log(doublePrices);
let staticPrices = doublePrices.map((v) => +(v / 34).toFixed(2));
log(staticPrices.join(" "));
let [head, ...tail] = staticPrices;
log(head);
log();
log("Tupels...");
let c1 = [1, 8.3];
let tup1 = ["abc", { ko: 2 }];
c1[0] *= 0.2;
log(c1, tup1);
let tup2 = [];
let tup3 = ["abc", "__3"];
function rePair(a, b) {
    return [a[0] + a[1], b[0] + b[1]];
}
let tup4 = rePair(c1, tup3);
log(tup4, tup2);
let tup5 = ["A", "__3"];
let tup6 = ["B"];
tup5 = tup6;
tup6 = tup5;
log(tup5, tup6);
let flags = ["FLAGS", true, false];
let [h, ...t] = flags;
log(flags, h, t);
